server :
  port : 8092

spring:
  datasource:
    url: jdbc:mysql://13.124.118.56/percol?useSSL=false&characterEncoding=UTF-8
    username: test
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache:false
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
